import type { Sector } from '@/types/stock'
export interface SectorConfig {
  industries: string[]; avgPE: number; avgBeta: number; avgDividendYield: number
  targetCount: number; debtEquityRange: [number,number]; companySuffixes: string[]
}
export const SECTOR_CONFIG: Record<Sector,SectorConfig> = {
  IT:{industries:['IT Services','Software Products','IT Consulting','BPO','Cloud Services'],avgPE:25,avgBeta:0.85,avgDividendYield:1.5,targetCount:600,debtEquityRange:[0,0.4],companySuffixes:['Tech','Systems','Infotech','Solutions','Digital','Soft']},
  Banking:{industries:['Private Banks','PSU Banks','Small Finance Banks','NBFC','Microfinance'],avgPE:18,avgBeta:1.1,avgDividendYield:1.2,targetCount:750,debtEquityRange:[6,14],companySuffixes:['Bank','Finance','Financial','Capital','Credit']},
  Pharma:{industries:['Pharmaceuticals','Biotechnology','Healthcare Services','Diagnostics','APIs'],avgPE:30,avgBeta:0.7,avgDividendYield:0.8,targetCount:500,debtEquityRange:[0,0.8],companySuffixes:['Pharma','Labs','Biotech','Healthcare','Life Sciences']},
  Auto:{industries:['Passenger Vehicles','Commercial Vehicles','Two Wheelers','Auto Components','EVs'],avgPE:22,avgBeta:1.05,avgDividendYield:1.0,targetCount:350,debtEquityRange:[0.1,1.8],companySuffixes:['Motors','Auto','Automotive','Vehicles','Components']},
  FMCG:{industries:['Personal Care','Food & Beverages','Household Products','Tobacco','Paints'],avgPE:35,avgBeta:0.6,avgDividendYield:1.8,targetCount:400,debtEquityRange:[0,0.4],companySuffixes:['Consumer','Foods','Products','Industries','Brands']},
  Metal:{industries:['Steel','Aluminum','Copper','Zinc','Mining','Pipes & Tubes'],avgPE:12,avgBeta:1.4,avgDividendYield:2.5,targetCount:300,debtEquityRange:[0.5,2.8],companySuffixes:['Steel','Metals','Mining','Industries','Alloys']},
  Energy:{industries:['Oil & Gas','Refineries','Power Generation','Renewable Energy','Gas Distribution'],avgPE:14,avgBeta:0.95,avgDividendYield:3.0,targetCount:300,debtEquityRange:[0.5,2.2],companySuffixes:['Power','Energy','Gas','Petroleum','Oil']},
  Realty:{industries:['Residential','Commercial','REITs','Construction'],avgPE:20,avgBeta:1.3,avgDividendYield:0.5,targetCount:350,debtEquityRange:[0.5,2.8],companySuffixes:['Realty','Properties','Developers','Housing','Estates']},
  Telecom:{industries:['Telecom Services','Telecom Equipment','Tower Infrastructure','Broadband'],avgPE:28,avgBeta:0.9,avgDividendYield:0.3,targetCount:200,debtEquityRange:[1.0,4.5],companySuffixes:['Telecom','Communications','Networks','Connect','Wireless']},
  Infrastructure:{industries:['Construction','Roads & Highways','Railways','Water','Airports'],avgPE:18,avgBeta:1.15,avgDividendYield:1.0,targetCount:400,debtEquityRange:[0.5,1.8],companySuffixes:['Infra','Infrastructure','Construction','Projects','Engineers']},
  Media:{industries:['Broadcasting','Print Media','Digital Media','OTT','Entertainment'],avgPE:28,avgBeta:0.9,avgDividendYield:0.3,targetCount:200,debtEquityRange:[0,0.8],companySuffixes:['Media','Entertainment','Studios','Digital','Network']},
  Chemicals:{industries:['Specialty Chemicals','Agrochemicals','Paints','Adhesives','Dyes'],avgPE:22,avgBeta:0.8,avgDividendYield:1.2,targetCount:350,debtEquityRange:[0,1.2],companySuffixes:['Chemicals','Industries','Organics','Petrochem','Polymers']},
  Others:{industries:['Retail','Aviation','Logistics','Textiles','Sugar','Fertilizers'],avgPE:16,avgBeta:1.0,avgDividendYield:1.5,targetCount:500,debtEquityRange:[0,1.8],companySuffixes:['Industries','Enterprises','Corp','Group','Ventures']},
}
export const ALL_SECTORS = Object.keys(SECTOR_CONFIG) as Sector[]
export type CompanyGroup = string
export interface RealCompany { symbol:string; name:string; sector:Sector; group:CompanyGroup; cap:'Large Cap'|'Mid Cap'|'Small Cap' }
/** Real NSE-listed companies, grouped by promoter group. Symbols are NSE tickers (Yahoo uses TICKER.NS).
 *  Run `npm run check:symbols` to verify every ticker against the live feed. */
export const LARGE_CAP_COMPANIES: RealCompany[] = [
  {symbol:'TCS',name:'Tata Consultancy Services',sector:'IT',group:'Tata',cap:'Large Cap'},
  {symbol:'TMPV',name:'Tata Motors Passenger Vehicles',sector:'Auto',group:'Tata',cap:'Large Cap'},
  {symbol:'TMCV',name:'Tata Motors Commercial Vehicles',sector:'Auto',group:'Tata',cap:'Large Cap'},
  {symbol:'TATASTEEL',name:'Tata Steel',sector:'Metal',group:'Tata',cap:'Large Cap'},
  {symbol:'TITAN',name:'Titan Company',sector:'Others',group:'Tata',cap:'Large Cap'},
  {symbol:'TATACONSUM',name:'Tata Consumer Products',sector:'FMCG',group:'Tata',cap:'Large Cap'},
  {symbol:'TATAPOWER',name:'Tata Power',sector:'Energy',group:'Tata',cap:'Large Cap'},
  {symbol:'TRENT',name:'Trent',sector:'Others',group:'Tata',cap:'Large Cap'},
  {symbol:'INDHOTEL',name:'Indian Hotels Company',sector:'Others',group:'Tata',cap:'Large Cap'},
  {symbol:'TATAELXSI',name:'Tata Elxsi',sector:'IT',group:'Tata',cap:'Mid Cap'},
  {symbol:'TATACOMM',name:'Tata Communications',sector:'Telecom',group:'Tata',cap:'Mid Cap'},
  {symbol:'VOLTAS',name:'Voltas',sector:'Others',group:'Tata',cap:'Mid Cap'},
  {symbol:'TATACHEM',name:'Tata Chemicals',sector:'Chemicals',group:'Tata',cap:'Mid Cap'},
  {symbol:'TATAINVEST',name:'Tata Investment Corporation',sector:'Banking',group:'Tata',cap:'Mid Cap'},
  {symbol:'TATATECH',name:'Tata Technologies',sector:'IT',group:'Tata',cap:'Mid Cap'},
  {symbol:'RELIANCE',name:'Reliance Industries',sector:'Energy',group:'Reliance (Jio)',cap:'Large Cap'},
  {symbol:'JIOFIN',name:'Jio Financial Services',sector:'Banking',group:'Reliance (Jio)',cap:'Large Cap'},
  {symbol:'NETWORK18',name:'Network18 Media & Investments',sector:'Media',group:'Reliance (Jio)',cap:'Small Cap'},
  {symbol:'TV18BRDCST',name:'TV18 Broadcast',sector:'Media',group:'Reliance (Jio)',cap:'Small Cap'},
  {symbol:'GRASIM',name:'Grasim Industries',sector:'Chemicals',group:'Aditya Birla',cap:'Large Cap'},
  {symbol:'HINDALCO',name:'Hindalco Industries',sector:'Metal',group:'Aditya Birla',cap:'Large Cap'},
  {symbol:'ULTRACEMCO',name:'UltraTech Cement',sector:'Infrastructure',group:'Aditya Birla',cap:'Large Cap'},
  {symbol:'ABCAPITAL',name:'Aditya Birla Capital',sector:'Banking',group:'Aditya Birla',cap:'Mid Cap'},
  {symbol:'ABSLAMC',name:'Aditya Birla Sun Life AMC',sector:'Banking',group:'Aditya Birla',cap:'Mid Cap'},
  {symbol:'ABREL',name:'Aditya Birla Real Estate',sector:'Realty',group:'Aditya Birla',cap:'Mid Cap'},
  {symbol:'ABFRL',name:'Aditya Birla Fashion & Retail',sector:'Others',group:'Aditya Birla',cap:'Small Cap'},
  {symbol:'ADANIENT',name:'Adani Enterprises',sector:'Others',group:'Adani',cap:'Large Cap'},
  {symbol:'ADANIPORTS',name:'Adani Ports & SEZ',sector:'Infrastructure',group:'Adani',cap:'Large Cap'},
  {symbol:'ADANIPOWER',name:'Adani Power',sector:'Energy',group:'Adani',cap:'Large Cap'},
  {symbol:'ADANIGREEN',name:'Adani Green Energy',sector:'Energy',group:'Adani',cap:'Large Cap'},
  {symbol:'ADANIENSOL',name:'Adani Energy Solutions',sector:'Energy',group:'Adani',cap:'Large Cap'},
  {symbol:'ATGL',name:'Adani Total Gas',sector:'Energy',group:'Adani',cap:'Mid Cap'},
  {symbol:'AMBUJACEM',name:'Ambuja Cements',sector:'Infrastructure',group:'Adani',cap:'Large Cap'},
  {symbol:'ACC',name:'ACC',sector:'Infrastructure',group:'Adani',cap:'Mid Cap'},
  {symbol:'AWL',name:'AWL Agri Business',sector:'FMCG',group:'Adani',cap:'Mid Cap'},
  {symbol:'M&M',name:'Mahindra & Mahindra',sector:'Auto',group:'Mahindra',cap:'Large Cap'},
  {symbol:'TECHM',name:'Tech Mahindra',sector:'IT',group:'Mahindra',cap:'Large Cap'},
  {symbol:'M&MFIN',name:'Mahindra & Mahindra Financial Services',sector:'Banking',group:'Mahindra',cap:'Mid Cap'},
  {symbol:'BAJFINANCE',name:'Bajaj Finance',sector:'Banking',group:'Bajaj',cap:'Large Cap'},
  {symbol:'BAJAJFINSV',name:'Bajaj Finserv',sector:'Banking',group:'Bajaj',cap:'Large Cap'},
  {symbol:'BAJAJ-AUTO',name:'Bajaj Auto',sector:'Auto',group:'Bajaj',cap:'Large Cap'},
  {symbol:'BAJAJHLDNG',name:'Bajaj Holdings & Investment',sector:'Banking',group:'Bajaj',cap:'Mid Cap'},
  {symbol:'HDFCBANK',name:'HDFC Bank',sector:'Banking',group:'HDFC',cap:'Large Cap'},
  {symbol:'HDFCLIFE',name:'HDFC Life Insurance',sector:'Banking',group:'HDFC',cap:'Large Cap'},
  {symbol:'HDFCAMC',name:'HDFC Asset Management',sector:'Banking',group:'HDFC',cap:'Mid Cap'},
  {symbol:'ICICIBANK',name:'ICICI Bank',sector:'Banking',group:'ICICI',cap:'Large Cap'},
  {symbol:'ICICIGI',name:'ICICI Lombard General Insurance',sector:'Banking',group:'ICICI',cap:'Large Cap'},
  {symbol:'ICICIPRULI',name:'ICICI Prudential Life Insurance',sector:'Banking',group:'ICICI',cap:'Mid Cap'},
  {symbol:'JSWSTEEL',name:'JSW Steel',sector:'Metal',group:'JSW',cap:'Large Cap'},
  {symbol:'JSWENERGY',name:'JSW Energy',sector:'Energy',group:'JSW',cap:'Large Cap'},
  {symbol:'JSWINFRA',name:'JSW Infrastructure',sector:'Infrastructure',group:'JSW',cap:'Mid Cap'},
  {symbol:'GODREJCP',name:'Godrej Consumer Products',sector:'FMCG',group:'Godrej',cap:'Large Cap'},
  {symbol:'GODREJPROP',name:'Godrej Properties',sector:'Realty',group:'Godrej',cap:'Mid Cap'},
  {symbol:'VEDL',name:'Vedanta',sector:'Metal',group:'Vedanta',cap:'Large Cap'},
  {symbol:'BHARTIARTL',name:'Bharti Airtel',sector:'Telecom',group:'Bharti',cap:'Large Cap'},
  {symbol:'SBIN',name:'State Bank of India',sector:'Banking',group:'Government (PSU)',cap:'Large Cap'},
  {symbol:'ONGC',name:'Oil & Natural Gas Corp',sector:'Energy',group:'Government (PSU)',cap:'Large Cap'},
  {symbol:'NTPC',name:'NTPC',sector:'Energy',group:'Government (PSU)',cap:'Large Cap'},
  {symbol:'POWERGRID',name:'Power Grid Corp',sector:'Energy',group:'Government (PSU)',cap:'Large Cap'},
  {symbol:'COALINDIA',name:'Coal India',sector:'Energy',group:'Government (PSU)',cap:'Large Cap'},
  {symbol:'IOC',name:'Indian Oil Corporation',sector:'Energy',group:'Government (PSU)',cap:'Large Cap'},
  {symbol:'BPCL',name:'Bharat Petroleum',sector:'Energy',group:'Government (PSU)',cap:'Large Cap'},
  {symbol:'GAIL',name:'GAIL (India)',sector:'Energy',group:'Government (PSU)',cap:'Large Cap'},
  {symbol:'LICI',name:'Life Insurance Corporation of India',sector:'Banking',group:'Government (PSU)',cap:'Large Cap'},
  {symbol:'BEL',name:'Bharat Electronics',sector:'Others',group:'Government (PSU)',cap:'Large Cap'},
  {symbol:'HAL',name:'Hindustan Aeronautics',sector:'Others',group:'Government (PSU)',cap:'Large Cap'},
  {symbol:'PNB',name:'Punjab National Bank',sector:'Banking',group:'Government (PSU)',cap:'Large Cap'},
  {symbol:'BANKBARODA',name:'Bank of Baroda',sector:'Banking',group:'Government (PSU)',cap:'Large Cap'},
  {symbol:'RECLTD',name:'REC',sector:'Banking',group:'Government (PSU)',cap:'Large Cap'},
  {symbol:'PFC',name:'Power Finance Corporation',sector:'Banking',group:'Government (PSU)',cap:'Large Cap'},
  {symbol:'IRCTC',name:'IRCTC',sector:'Others',group:'Government (PSU)',cap:'Mid Cap'},
  {symbol:'NMDC',name:'NMDC',sector:'Metal',group:'Government (PSU)',cap:'Mid Cap'},
  {symbol:'SAIL',name:'Steel Authority of India',sector:'Metal',group:'Government (PSU)',cap:'Mid Cap'},
  {symbol:'INFY',name:'Infosys',sector:'IT',group:'Independent',cap:'Large Cap'},
  {symbol:'WIPRO',name:'Wipro',sector:'IT',group:'Independent',cap:'Large Cap'},
  {symbol:'HCLTECH',name:'HCL Technologies',sector:'IT',group:'Independent',cap:'Large Cap'},
  {symbol:'HINDUNILVR',name:'Hindustan Unilever',sector:'FMCG',group:'Independent',cap:'Large Cap'},
  {symbol:'ITC',name:'ITC',sector:'FMCG',group:'Independent',cap:'Large Cap'},
  {symbol:'NESTLEIND',name:'Nestle India',sector:'FMCG',group:'Independent',cap:'Large Cap'},
  {symbol:'BRITANNIA',name:'Britannia Industries',sector:'FMCG',group:'Independent',cap:'Large Cap'},
  {symbol:'KOTAKBANK',name:'Kotak Mahindra Bank',sector:'Banking',group:'Independent',cap:'Large Cap'},
  {symbol:'AXISBANK',name:'Axis Bank',sector:'Banking',group:'Independent',cap:'Large Cap'},
  {symbol:'INDUSINDBK',name:'IndusInd Bank',sector:'Banking',group:'Independent',cap:'Large Cap'},
  {symbol:'SBILIFE',name:'SBI Life Insurance',sector:'Banking',group:'Independent',cap:'Large Cap'},
  {symbol:'SHRIRAMFIN',name:'Shriram Finance',sector:'Banking',group:'Independent',cap:'Large Cap'},
  {symbol:'LT',name:'Larsen & Toubro',sector:'Infrastructure',group:'Independent',cap:'Large Cap'},
  {symbol:'MARUTI',name:'Maruti Suzuki India',sector:'Auto',group:'Independent',cap:'Large Cap'},
  {symbol:'EICHERMOT',name:'Eicher Motors',sector:'Auto',group:'Independent',cap:'Large Cap'},
  {symbol:'HEROMOTOCO',name:'Hero MotoCorp',sector:'Auto',group:'Independent',cap:'Large Cap'},
  {symbol:'SUNPHARMA',name:'Sun Pharmaceutical',sector:'Pharma',group:'Independent',cap:'Large Cap'},
  {symbol:'DRREDDY',name:'Dr Reddys Laboratories',sector:'Pharma',group:'Independent',cap:'Large Cap'},
  {symbol:'CIPLA',name:'Cipla',sector:'Pharma',group:'Independent',cap:'Large Cap'},
  {symbol:'DIVISLAB',name:'Divis Laboratories',sector:'Pharma',group:'Independent',cap:'Large Cap'},
  {symbol:'LUPIN',name:'Lupin',sector:'Pharma',group:'Independent',cap:'Large Cap'},
  {symbol:'APOLLOHOSP',name:'Apollo Hospitals',sector:'Pharma',group:'Independent',cap:'Large Cap'},
  {symbol:'ASIANPAINT',name:'Asian Paints',sector:'Chemicals',group:'Independent',cap:'Large Cap'},
  {symbol:'PIDILITIND',name:'Pidilite Industries',sector:'Chemicals',group:'Independent',cap:'Large Cap'},
  {symbol:'ETERNAL',name:'Eternal (Zomato)',sector:'Others',group:'Independent',cap:'Large Cap'},
  {symbol:'DMART',name:'Avenue Supermarts (DMart)',sector:'Others',group:'Independent',cap:'Large Cap'},
  {symbol:'DLF',name:'DLF',sector:'Realty',group:'Independent',cap:'Large Cap'},
]
export const COMPANY_GROUPS: string[] = Array.from(new Set(LARGE_CAP_COMPANIES.map(c => c.group)))
// Index membership shown in the grid (kept to the original 30 blue chips; Tata Motors is now TMPV after the 2025 demerger)
export const NIFTY50_SYMBOLS: string[] = ['RELIANCE','TCS','HDFCBANK','INFY','ICICIBANK','HINDUNILVR','ITC','KOTAKBANK','LT','AXISBANK','SBIN','WIPRO','HCLTECH','MARUTI','SUNPHARMA','ONGC','TMPV','TITAN','BAJFINANCE','ASIANPAINT','NTPC','POWERGRID','TATASTEEL','NESTLEIND','DRREDDY','CIPLA','TECHM','ULTRACEMCO','BAJAJFINSV','GRASIM']
// Jio Platforms is not listed yet (IPO pending). Once it lists, add its NSE ticker to LARGE_CAP_COMPANIES with group 'Reliance (Jio)'.
/** Symbols that are real NSE-listed companies -> get real prices from the live feed. */
export const REAL_SYMBOLS: string[] = LARGE_CAP_COMPANIES.map(c => c.symbol)
